version: "3.9"

services:

  postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5434:5432"
    volumes:
      - catalogue_postgres_data:/var/lib/postgresql/data
      - ./infra/postgres-init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: shop
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend-service:
    build: backend-java/
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shop
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      REDIS_HOST: redis
      RABBITMQ_HOST: rabbitmq
      MINIO_ENDPOINT: minio:9000
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
      minio:
        condition: service_started

  worker:
    build: order-worker-python/
    restart: unless-stopped
    environment:
      DB_URL: postgres://${SPRING_DATASOURCE_USERNAME}:${SPRING_DATASOURCE_PASSWORD}@postgres:5432/shop
      RABBITMQ_HOST: rabbitmq
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  auth-service:
    build: auth-service-go/
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      REDIS_ADDR: redis:6379
      ETCD_ENDPOINTS: etcd:2379
    depends_on:
      redis:
        condition: service_started
      etcd:
        condition: service_started

  frontend:
    build: frontend-react
    restart: unless-stopped

  nginx-gateway:
    image: nginx:stable-alpine
    container_name: nginx-gateway
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./nginx-gateway/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend-service
      - auth-service
      - minio

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  etcd:
    image: quay.io/coreos/etcd:v3.5.16
    container_name: etcd
    restart: unless-stopped
    command:
      - /usr/local/bin/etcd
      - --name=s1
      - --data-dir=/etcd-data
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://etcd:2379
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-advertise-peer-urls=http://etcd:2380
      - --initial-cluster=s1=http://etcd:2380
      - --initial-cluster-token=etcd-cluster-1
      - --initial-cluster-state=new
    ports:
      - "2379:2379"
    volumes:
      - etcd_data:/etcd-data

  minio:
    image: minio/minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    volumes:
      - ./infra/minio-init/init.sh:/scripts/init.sh
      - ./infra/generated-images:/data/images
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_URL: http://minio:9000
    entrypoint: /bin/sh /scripts/init.sh

volumes:
  catalogue_postgres_data:
  etcd_data:
  minio_data: