apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: hello
  ports:
    - protocol: TCP
      port: 80      # Порт, на котором сервис будет доступен внутри кластера
      targetPort: 5001 # Порт, который слушает Python